### PR TITLE
fix: If a remote profile failed to open, the user cannot open it again

### LINKED ISSUE #642: [Formatting Preview] If a remote profile failed to open by some network issue, the user cannot open it again
If a remote profile failed to open by some network issue, the user cannot open it again.

btw, the error message can be better as well, instead of simply throw out the raw error message

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #642

### CODE REVIEW

File: src/formatter-settings/utils.ts [hunk 1]
```diff
@@ -156,7 +156,18 @@ export function parseProfile(document: vscode.TextDocument): ProfileContent {
 }
 
 export async function downloadFile(settingsUrl: string): Promise<string> {
-    return (await axios.get(settingsUrl)).data;
+    let content = "";
+    try {
+        content = (await axios.get(settingsUrl)).data;
```
Comment (jdneo) [inline src/formatter-settings/utils.ts:161]: directly return `(await axios.get(settingsUrl)).data;`

**Review by jdneo — APPROVED** [review]
